### ISSUE TITLE
Figure out what is crashing Vite Node Bot

### ISSUE THREAD

**Issue by JohnGarnham** [ViNo-community/vite-node-bot#18]
For some reason Vite Node Bot is randomly crashing. Possible null pointer. Figure out what is crashing it (add logging) and fix. Seems to be related to network issue, not a specific command. May just be my ISP and not my bot - so deploying it to server may fix - but need to look into more.

**Comment by JohnGarnham** [comment]
I have a suspicion that it is a permissions issue because I have been editing files and running the bot as root. Which then might cause permissions issue if I try to run it as a normal user. Once I add logging the cause will become more clear.

**Comment by JohnGarnham** [comment]
Could be related: 
```
Could not retrieve info for ViNo_Community_Node} Error: Invalid JSON RPC response: null
    at Object.INVAILID_RESPONSE (/home/john/Projects/vite_node_bot/node_modules/@vite/vitejs-http/dist/index.node.js:1:1695)
    at /home/john/Projects/vite_node_bot/node_modules/@vite/vitejs-http/dist/index.node.js:1:6624
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/home/john/Projects/vite_node_bot/commands/sbp.js:70
            console.error("Error while grabbing SBP rewards summary :" + error.message);
                                                                               ^

TypeError: Cannot read property 'message' of undefined
    at /home/john/Projects/vite_node_bot/commands/sbp.js:70:80
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by JohnGarnham** [comment]
Null pointer on error. Covered on #21
