### ISSUE TITLE
Null pointer in v!balance

### ISSUE THREAD

**Issue by JohnGarnham** [ViNo-community/vite-node-bot#21]
Looking up info for address: vite_48171fc674cffc8cc4e0b2e7544ba468d31cbdce1fc35cba02

Could not account retrieve info for vite_48171fc674cffc8cc4e0b2e7544ba468d31cbdce1fc35cba02  Error: Invalid JSON RPC response: null
    at Object.INVAILID_RESPONSE (/home/john/Projects/vite_node_bot/node_modules/@vite/vitejs-http/dist/index.node.js:1:1695)
    at /home/john/Projects/vite_node_bot/node_modules/@vite/vitejs-http/dist/index.node.js:1:6624
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/home/john/Projects/vite_node_bot/commands/balance.js:68
            console.error("Error while grabbing account summary :" + error.message);

**Comment by JohnGarnham** [comment]
Fixed to handle null response without crashing, but cannot consistently replicate null response for !balance .
Will keep an eye on it.

**Comment by JohnGarnham** [comment]
Issue is resolved
