### ISSUE TITLE
v!contract message too long for discord

### ISSUE THREAD

**Issue by JohnGarnham** [ViNo-community/vite-node-bot#28]
v!contract [smart contract address] has a message too long for discord:

```
/home/john/Projects/Vite-Bot/vite-node-bot/node_modules/discord.js/src/rest/RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at RequestHandler.execute (/home/john/Projects/Vite-Bot/vite-node-bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/john/Projects/Vite-Bot/vite-node-bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/844020493450477642/messages',
  code: 50035,
  httpStatus: 400
```

Solution: Break up message into < 2000 sized chunks. There's examples of this elsewhere in code, like votes.

**Comment by JohnGarnham** [comment]
Not sure why my commit didn't close it.
